///////////////////////////////////////////////////////////
//  IAstDataBase.cs
//  Implementation of the Interface IAstDataBase
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:28:45
//  Original author: ajith.padman
///////////////////////////////////////////////////////////





using CCodeTypes.Types;
using CCodeTypes.Xml;

namespace CCodeFramework.Interfaces
{
    public interface IAstDataBase  {

		/// 
		/// <param name="Element">element to be added to the Database</param>
		void AstDB_AddElement( CElement Element);

		/// <summary>
		/// Find if an element exists in database add it if not existing
		/// </summary>
		/// <param name="Element">Find an element if exists or add to database if
		/// not</param>
		CElement AstDB_FindAndAddElement( CElement Element);

		/// <summary>
		/// Check if an element of similar type Exists in the Database
		/// if exists return that object else return Null pointer
		/// </summary>
		/// <param name="ElementID"> ID of the element to be retrieved</param>
		CElement AstDB_FindElement(string ElementID);

        CXml PublishDataBase(string FilePath);
	}//end IAstDataBase

}//end namespace Interfaces