///////////////////////////////////////////////////////////
//  ICParser.cs
//  Implementation of the Interface ICParser
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:28:45
//  Original author: ajith.padman
///////////////////////////////////////////////////////////




using CCodeTypes.Types;
using ClangSharp;
namespace CCodeFramework.Interfaces
{
    public interface ICParser  {

        /// 
        /// <param name="Cursor"></param>
        CElement CParser_VisitFunctionCursor(Cursor Cursor);

        /// 
        /// <param name="Cursor"></param>
        CElement CParser_VisitVariableCursor(Cursor Cursor);

      
	}//end ICParser

}//end namespace Interfaces