///////////////////////////////////////////////////////////
//  ICTypeParser.cs
//  Implementation of the Interface ICTypeParser
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:28:45
//  Original author: ajith.padman
///////////////////////////////////////////////////////////



using CCodeTypes.Types;

namespace CCodeFramework.Interfaces
{
    public interface ICTypeParser  {

		/// 
		/// <param name="Type"></param>
		CElement CTypeParser_ParseDataType(ClangSharp.Type Type);

		/// 
		/// <param name="type"></param>
		CElement visitArithMeticType(ClangSharp.Type type);

		/// 
		/// <param name="type"></param>
		CElement visitArrayType(ClangSharp.Type type);

		/// 
		/// <param name="Type"></param>
		CElement visitEnumType(ClangSharp.Type Type);

		/// 
		/// <param name="type"></param>
		CElement visitPointerType(ClangSharp.Type type);

		/// 
		/// <param name="type"></param>
		CElement visitStructOrUnionType(ClangSharp.Type type);

		/// 
		/// <param name="type"></param>
		CElement visitTypeDefType(ClangSharp.Type type);
	}//end ICTypeParser

}//end namespace Interfaces