///////////////////////////////////////////////////////////
//  IFactory.cs
//  Implementation of the Interface IFactory
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:28:45
//  Original author: ajith.padman
///////////////////////////////////////////////////////////

using CCodeTypes.Types;
using CCodeTypes.Xml;
using System.Collections.Generic;

namespace CCodeFramework.Interfaces
{
    public interface IFactory  {

     

        ProjectModel Fac_getProjectModel(string[] Args);
        IAstDataBase Fac_getDataBase();
        ICTypeParser fac_getTypeParser();
        ICParser fac_getCParser();
        IClang Fac_getClangInterface();
        string Fac_GetComponentName(CElement function);
        string Fac_GetInterfaceName(CFunction function);
        Function Fac_GetXmlFunctionType(CFunction f);
        Variable Fac_GetXmlVariableType(CVariable v);
        DataType Fac_GetXmlDataType(CDataType d);
        Dictionary<string,string> Fac_GetSWCConfig();

        Dictionary<string, SWCType> Fac_GetSWCType();

    }//end IFactory

}//end namespace Interfaces