///////////////////////////////////////////////////////////
//  CFunction.cs
//  Implementation of the Class CFunction
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:29:33
//  Original author: ajith.padman
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace CCodeTypes.Types
{
    public class CFunction : CElement {

		/// <summary>
		/// Children C elements of the Function
		/// which are the functions called by the function
		/// </summary>
		public List<string> Children;
		/// <summary>
		/// the function is a definition of declairation
		/// </summary>
		public bool IsDefinition;
        /// <summary>
        /// Has calculated over ReturnType and ParameterTypes
        /// </summary>
        public string ProtoTypeHash;
        
		/// <summary>
		/// Parameters of the funtion
		/// </summary>
		public List<CElement> Parameters;
		/// <summary>
		/// Qualifier for the function
		/// </summary>
		public Qualifier Qualifier;
		/// <summary>
		/// Reference to the return Type ID
		/// </summary>
		public string ReturnType;
		public StorageClass StorageClass;

		public CFunction(){
            Parameters = new List<CElement>();
            Children = new List<string>();

        }

		~CFunction(){

		}

	}//end CFunction

}//end namespace Types