///////////////////////////////////////////////////////////
//  CVariable.cs
//  Implementation of the Class CVariable
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:29:33
//  Original author: ajith.padman
///////////////////////////////////////////////////////////






namespace CCodeTypes.Types
{
    public class CVariable : CElement {

		public string Type;
		public string Value;
        public VariableType VariableType;
        public CVariable(){

		}

		~CVariable(){

		}

	}//end CVariable

}//end namespace Types