///////////////////////////////////////////////////////////
//  DataTypeKind.cs
//  Implementation of the Enumeration DataTypeKind
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:29:33
//  Original author: ajith.padman
///////////////////////////////////////////////////////////




namespace CCodeTypes.Types
{
    public enum DataTypeKind : int {

		/// <summary>
		/// Arithmetic type of data usually basic types provided by C
		/// </summary>
		ARITHMETIC_TYPE,
		/// <summary>
		/// Array type
		/// </summary>
		ARRAY_TYPE,
		/// <summary>
		/// Structure kind
		/// </summary>
		STRUCT_TYPE,
		/// <summary>
		/// Union Kind
		/// </summary>
		UNION_TYPE,
		/// <summary>
		/// Pointer to something
		/// </summary>
		POINTER_TYPE,

        FUNCTION_POINTER,
		/// <summary>
		/// Typedef of some other datatype
		/// </summary>
		TYPEDEF_TYPE,
		/// <summary>
		/// Enumeration Literal type
		/// </summary>
		LITERAL_TYPE,

        ENUM_TYPE,

        FUNCTION_PROTOTYPE


	}//end DataTypeKind

}//end namespace Types