///////////////////////////////////////////////////////////
//  ElementKind.cs
//  Implementation of the Enumeration ElementKind
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:29:33
//  Original author: ajith.padman
///////////////////////////////////////////////////////////




namespace CCodeTypes.Types
{
    public enum ElementKind : int {

		/// <summary>
		/// Element in the code of type Function
		/// </summary>
		Function,
		/// <summary>
		/// Variable type element
		/// </summary>
		Variable,
		/// <summary>
		/// Type information element
		/// </summary>
		DataType

	}//end ElementKind

}//end namespace Types