///////////////////////////////////////////////////////////
//  ProjectModel.cs
//  Implementation of the Class ProjectModel
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:29:33
//  Original author: ajith.padman
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.IO;



namespace CCodeTypes.Types
{
    public class ProjectModel {

		public List<string> ClangOptions;
		public string CodeXmlModel = "CodeModel.xml";
        public string UmlModel =  "Uml.xmi";
        public string SrcListFile = "";
		public List<string> CommonHeaders;
		public List<string> HeaderFiles;
		public List<string> IncludePaths;
        public List<string> SourcePaths;
        public List<string> Libraries;
		public List<string> LibraryPaths;
		public List<string> MacroDefines;
		public string RootDir ;
		public List<string> SourceFiles;
        public string SWCConfig;

		public ProjectModel(){
            ClangOptions = new List<string>();
            CommonHeaders = new List<string>();
            HeaderFiles = new List<string>();
            IncludePaths = new List<string>();
            SourcePaths = new List<string>();
            Libraries = new List<string>();
            LibraryPaths = new List<string>();
            MacroDefines = new List<string>();
            SourceFiles = new List<string>();
            RootDir = Directory.GetCurrentDirectory();

        }
        
        ~ProjectModel(){

		}

	}//end ProjectModel

}//end namespace Types