///////////////////////////////////////////////////////////
//  Qualifier.cs
//  Implementation of the Enumeration Qualifier
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:29:33
//  Original author: ajith.padman
///////////////////////////////////////////////////////////




namespace CCodeTypes.Types
{
    public enum Qualifier : int {
        INVALID,

		/// <summary>
		/// Const qualifier
		/// </summary>
		CONST,
		/// <summary>
		/// Volatile qualifier
		/// </summary>
		VOLATILE

	}//end Qualifier

}//end namespace Types