///////////////////////////////////////////////////////////
//  StorageClass.cs
//  Implementation of the Enumeration StorageClass
//  Generated by Enterprise Architect
//  Created on:      15-Dez-2017 13:29:33
//  Original author: ajith.padman
///////////////////////////////////////////////////////////




namespace CCodeTypes.Types
{
    public enum StorageClass : int {

        Invalid, None, Extern, Static, PrivateExtern, CX_SC_OpenCLWorkGroupLocal, Auto, Register

    }//end StorageClass

}//end namespace Types